
/*
 * 
 */

package com.dgti.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Nov 14 10:19:29 CST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "RegistraArtista", 
                  wsdlLocation = "http://localhost:8080/pixup-eb/RegistraArtista/RegsitraArtista?wsdl",
                  targetNamespace = "http://ejb.dgti.com/") 
public class RegistraArtista_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ejb.dgti.com/", "RegistraArtista");
    public final static QName RegsitraArtistaPort = new QName("http://ejb.dgti.com/", "RegsitraArtistaPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/pixup-eb/RegistraArtista/RegsitraArtista?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/pixup-eb/RegistraArtista/RegsitraArtista?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public RegistraArtista_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegistraArtista_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistraArtista_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
//    public RegistraArtista_Service(WebServiceFeature ... features) {
//        super(WSDL_LOCATION, SERVICE, features);
//    }
//    public RegistraArtista_Service(URL wsdlLocation, WebServiceFeature ... features) {
//        super(wsdlLocation, SERVICE, features);
//    }
//
//    public RegistraArtista_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
//        super(wsdlLocation, serviceName, features);
//    }

    /**
     * 
     * @return
     *     returns RegsitraArtista
     */
    @WebEndpoint(name = "RegsitraArtistaPort")
    public RegsitraArtista getRegsitraArtistaPort() {
        return super.getPort(RegsitraArtistaPort, RegsitraArtista.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegsitraArtista
     */
    @WebEndpoint(name = "RegsitraArtistaPort")
    public RegsitraArtista getRegsitraArtistaPort(WebServiceFeature... features) {
        return super.getPort(RegsitraArtistaPort, RegsitraArtista.class, features);
    }

}
