package com.dgti.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Nov 14 10:19:29 CST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://ejb.dgti.com/", name = "RegsitraArtista")
@XmlSeeAlso({ObjectFactory.class})
public interface RegsitraArtista {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registraArtista", targetNamespace = "http://ejb.dgti.com/", className = "com.dgti.ws.RegistraArtista")
    @WebMethod
    @ResponseWrapper(localName = "registraArtistaResponse", targetNamespace = "http://ejb.dgti.com/", className = "com.dgti.ws.RegistraArtistaResponse")
    public int registraArtista(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
