
package edu.dgsca.ws.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WebServiceSample", targetNamespace = "http://edu.dgsca.ws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceSample {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registraPeticion", targetNamespace = "http://edu.dgsca.ws", className = "edu.dgsca.ws.cliente.RegistraPeticion")
    @ResponseWrapper(localName = "registraPeticionResponse", targetNamespace = "http://edu.dgsca.ws", className = "edu.dgsca.ws.cliente.RegistraPeticionResponse")
    public String registraPeticion(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
