
package edu.dgsca.ws.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "webServiceSample", targetNamespace = "http://edu.dgsca.ws", wsdlLocation = "http://localhost:7777/wssample?wsdl")
public class WebServiceSample_Service
    extends Service
{

    private final static URL WEBSERVICESAMPLE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(edu.dgsca.ws.cliente.WebServiceSample_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = edu.dgsca.ws.cliente.WebServiceSample_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:7777/wssample?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:7777/wssample?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICESAMPLE_WSDL_LOCATION = url;
    }

    public WebServiceSample_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceSample_Service() {
        super(WEBSERVICESAMPLE_WSDL_LOCATION, new QName("http://edu.dgsca.ws", "webServiceSample"));
    }

    /**
     * 
     * @return
     *     returns WebServiceSample
     */
    @WebEndpoint(name = "webServiceSamplePort")
    public WebServiceSample getWebServiceSamplePort() {
        return super.getPort(new QName("http://edu.dgsca.ws", "webServiceSamplePort"), WebServiceSample.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceSample
     */
    @WebEndpoint(name = "webServiceSamplePort")
    public WebServiceSample getWebServiceSamplePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://edu.dgsca.ws", "webServiceSamplePort"), WebServiceSample.class, features);
    }

}
